import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "../components/navigation/main-header";
import GoogleMapsLayout from "@/app/(maps)/mapsTest/layout";

import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "@/contexts/contextCarrito";

import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AssistASAP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <ClerkProvider 
        appearance={{
          
        }}
      >
        <html lang="en">
          <body className="">
            <GoogleMapsLayout>
              {/*Main header para manejar las rutas*/}
              <MainHeader content={children} />
              <Toaster/>
            </GoogleMapsLayout>
          </body>
        </html>
      </ClerkProvider>
    </CartProvider>
  );
}
